In [3]:
import numpy as np
import pandas as pd

In [5]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [8]:
df=pd.read_csv('covid_toy.csv')
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [9]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [11]:
X_train

    age  gender  fever   cough       city
1    27    Male  100.0    Mild      Delhi
40   49  Female  102.0    Mild      Delhi
30   15    Male  101.0    Mild      Delhi
10   75  Female    NaN    Mild      Delhi
70   68  Female  101.0  Strong      Delhi
..  ...     ...    ...     ...        ...
89   46    Male  103.0  Strong  Bangalore
98    5  Female   98.0  Strong     Mumbai
69   73  Female  103.0    Mild      Delhi
80   14  Female   99.0    Mild     Mumbai
78   11    Male  100.0    Mild  Bangalore

[80 rows x 5 columns]